### ISSUE TITLE
"Boop has stopped working"

### ISSUE THREAD

**Issue by nikitaluger** [miltoncandelero/Boop#9]
Pressing "BOOP" will close the program followed by a "Boop has stopped working" notification. On Windows 10.
![untitled](https://cloud.githubusercontent.com/assets/20486047/21477954/d3f55ce2-cb57-11e6-9fd4-ffa8dc864de7.jpg)

**Comment by miltoncandelero** [comment]
Are you sure that 192.168.1.1 is the ip for your 3ds?

**Comment by nikitaluger** [comment]
No its not the ip address. It's 192.168.100.XXX but it wouldn't matter. I just did that to make a screenshot. The error will occur as soon as I press "BOOP" even if set it up properly (or not)

**Comment by miltoncandelero** [comment]
mmm well I can assure you that if the IP is wrong you WILL freeze.

On version 1.0 the socket connection to the 3ds doesn't have a timeout so it waits forever (and thus hanging the program).

The timeout problem is fixed now, but unless you compile it yourself you will have to wait to the next release (coming today or tomorrow).

Then we will see if it still happens.

**Comment by nikitaluger** [comment]
I'll just wait for the next release. I anticipated that a bug or two comes with the 1.0 release. Thank you for Boop BTW. Now I can use the latest FBI releases. :)

Keep ut the good work.

**Comment by miltoncandelero** [comment]
1.0.1 is out with the socket timeout. Check if the error is still there :)

**Comment by nikitaluger** [comment]
Kudos for the quick update but unfortunately the problem still persists. Is there something that I'm doing wrong? Something I need to install in my PC to avoid the crash? I wish there was something I could send you to find out what's causing the error like a log or something.

![20161226_205319](https://cloud.githubusercontent.com/assets/20486047/21485127/da4d9b5c-cbae-11e6-9dd0-b670df42e523.jpg)

**Comment by miltoncandelero** [comment]
:| This gets weirder and weirder.

Try this: Make sure that you are running the new version and try connecting to a wrong Ip adress (for instance 200.200.200.200).

After 5 seconds (the app will feel frozen, wait for it) a popup should say that the IP adress is wrong.

If that doesn't trigger then you are crashing before the connection is attempted

**Comment by nikitaluger** [comment]
I did as instructed and the crash definitely happens before the connection is attempted. As soon as I click BOOP its gone...

![untitled](https://cloud.githubusercontent.com/assets/20486047/21485229/cd8d794e-cbb0-11e6-9b8f-d6a3da9b4873.jpg)

**Comment by miltoncandelero** [comment]
Ok, let's try one by one all the things that happen before the timeout.

Try this:

* Open cmd (Windors + R -> type CMD -> enter)
* Type "netsh" (no quotes) and press enter.
* You should get "netsh>"
* Close the window and report back

Maybe netsh (the thingy I use to lift the firewall) is not present in your system?

**Comment by nikitaluger** [comment]
I did as instructed:

![untitled](https://cloud.githubusercontent.com/assets/20486047/21485512/aca4e122-cbb5-11e6-8e10-35e69744f41c.jpg)

I also tried running Boop with Windows Firewall disabled and the program still crashes like before.

**Comment by miltoncandelero** [comment]
[Boop debug.zip](https://github.com/miltoncandelero/Boop/files/673257/Boop.debug.zip)
Okay. This is it.

If anything tries to go wrong we should get a message explaining where it went wrong.
Try this on. (Is a debug version, it looks horrible but should do the trick)

**Comment by nikitaluger** [comment]
I'm sorry but... 
![untitled](https://cloud.githubusercontent.com/assets/20486047/21485930/722e5be8-cbbc-11e6-9594-9554e6e25543.jpg)

Was it supposed to leave an error log? Nothing was generated after the crash. But something did happen while I was messing around with the debug ver... My 3DS sort of went to that Accept/Cancel notification. It's a hit-or-miss type deal although. Accepting the file will just give me a 404 error. I can also see that my 3DS wifi led responds to Boop (blinks a few times) when I close the error notification on my PC. I can confirm that Boop sometimes gets to communicate with the 3DS before it crashes: 

![15608609_10211850664841834_1786399878_o](https://cloud.githubusercontent.com/assets/20486047/21486075/ca19787c-cbbe-11e6-94cd-259e151e5bac.jpg)

**Comment by miltoncandelero** [comment]
Ok. Your computer is officially possessed.

I wrapped all the code in that button inside a try-catch block.

A Try-Catch block is designed to try something and catch the errors.

The program crashing means that the error was not caught...

**This should not happen at all!**

My brain is dry.

I hope somebody on the internet has any idea on why this might be happening

**Comment by LeoLamCY** [comment]
From the screenshots, the 404 is caused by the %20's in the file name which SHOULD be replaced by spaces before SimpleHTTPServer goes and looks for the file in the file system. 
Does the latest release include all the changes I made yesterday? If it does then this shouldn't be happening at all.
I'm not home right now so I can't test it myself.

**Comment by miltoncandelero** [comment]
@LeoLamCY Yes it does. I tested and is not the spaces nor the pharentesis in the file name. (your code works great. yay!)

In any case this shouldn't cause a crash like that.

Furthermore, I wrapped all the code in the button with a Try-Catch (the modified exe I posted above) and it still crashes. It is Really confusing :(

**Comment by LeoLamCY** [comment]
Yea, the 404 wasn't the cause of the crashes but I was wondering why it happened. 

Anyway, I think this is definitely caused by the netsh command that pokes a hole in the firewall, but why? I'm not sure. You can see the status bar still read "Ready" when he crashed so it definitely crashed before `setStatusLabel("Booping... please wait");` and anything before the netsh code doesn't look like it could create a crash. Could it be because the program doesn't have admin rights as required and netsh makes the program crash?

@nikitaluger
Do you see a box like in the attached image when you run the program?
![capture](https://cloud.githubusercontent.com/assets/4132984/21490398/21802a7c-cbc2-11e6-9fe7-df28e2e9ed55.JPG)

**Comment by nikitaluger** [comment]
Sorry it took so long for me to reply I just got back from work... Anyway @LeoLamCY, I get this notification when I run Boop.exe right after downloading and my PC only gives me this notification once.

![untitled](https://cloud.githubusercontent.com/assets/20486047/21501391/9029348c-cc58-11e6-8241-a5ff3253142d.jpg)

This is what I get each time I try to run Boop.exe. I also get said notification after the one above.

![15748854_10211857602495271_1273875065_o](https://cloud.githubusercontent.com/assets/20486047/21501415/c5f3f5ca-cc58-11e6-98e5-ad48624fb2eb.jpg)

**Comment by nikitaluger** [comment]
I tried using Boop.exe on my laptop but I still get a crash. The first try showed "Booping... please wait" but I can never reproduce it again. Also FBI on 3DS gave me a 101 (i think) error during one of my tries.

![untitled](https://cloud.githubusercontent.com/assets/20486047/21501681/08dfb4e4-cc5b-11e6-85dd-88a9becfe486.jpg)

**Comment by nikitaluger** [comment]
Boop now works with 1.1.1 release. Awesome work guys! Many thanks to the hard work fixing the issue.
